apiVersion: v1
kind: Service
metadata:
  name: event-bus-np
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - port: 4222
      nodePort: 30030
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-np2
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - port: 8222
      nodePort: 30031
