apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MONGO_INITDB_ROOT_USERNAME: mongo
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_URL: db-srv:27017
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mongo
          envFrom:
            - configMapRef:
                name: db-config
          volumeMounts:
            - mountPath: /data/db
              name: db-v
      volumes:
        - name: db-v
          persistentVolumeClaim:
            claimName: db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-srv
spec:
  selector:
    app: db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db-srv-np
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - port: 27017
      nodePort: 30000
