apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
data:
  CACHE_PASSWORD: password
  CACHE_HOST: cache-srv
  CACHE_PORT: "6379"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cache-pv
  labels:
    type: local
    app: cache
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/cache"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-pv-claim
  labels:
    app: cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis
          command:
            - "redis-server"
          args: ["--requirepass", $(CACHE_PASSWORD)]
          env:
            - name: CACHE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cache-config
                  key: CACHE_PASSWORD
          volumeMounts:
            - mountPath: /data
              name: cache-v
      volumes:
        - name: cache-v
          persistentVolumeClaim:
            claimName: cache-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cache-srv
spec:
  selector:
    app: cache
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cache-srv-np
spec:
  type: NodePort
  selector:
    app: cache
  ports:
    - port: 6379
      nodePort: 30001
