apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
data:
  MONGO_INITDB_ROOT_USERNAME: mongo
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_URL: accounts-db-srv:27017
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: accounts-db-pv
  labels:
    type: local
    app: accounts-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data/accounts-db'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: accounts-db-pv-claim
  labels:
    app: accounts-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
spec:
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
      containers:
        - name: accounts-db
          image: mongo
          envFrom:
            - configMapRef:
                name: accounts-db-config
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          volumeMounts:
            - mountPath: /data/db
              name: accounts-db-v
      volumes:
        - name: accounts-db-v
          persistentVolumeClaim:
            claimName: accounts-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db-srv
spec:
  selector:
    app: accounts-db
  ports:
    - port: 27017
      targetPort: 27017
