apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: micro-shop/accounts
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: accounts-db-config
            - configMapRef:
                name: event-bus-config
          env:
            - name: NODE_ENV
              value: DEVELOPMENT
            - name: JWT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: JWT_ACCESS_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: JWT_REFRESH_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-srv
spec:
  selector:
    app: accounts
  ports:
    - port: 3000
      targetPort: 3000
