apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
spec:
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: nats-streaming
          args:
            [
              "-p",
              "4222",
              "-m",
              "8222",
              "-hbi",
              "5s",
              "-hbt",
              "5s",
              "-hbf",
              "2",
              "-SD",
              "-cid",
              "micro-shop",
            ]
          ports:
            - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  ports:
    - port: 4222
      targetPort: 4222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-bus-config
data:
  EVENT_BUS_URL: http://event-bus-srv:4222
