apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: micro-shop/cart
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: event-bus-config
          env:
            - name: NODE_ENV
              value: DEVELOPMENT
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  ports:
    - port: 3000
      targetPort: 3000
