apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: micro-shop/products
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: products-db-config
            - configMapRef:
                name: event-bus-config
          env:
            - name: DATABASE_SSL
              value: 'false'
            - name: NODE_ENV
              value: DEVELOPMENT
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - port: 3000
      targetPort: 3000
