apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: micro-shop/products
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: POSTGRES_URL
          value: products-db-srv:5432
        - name: DATABASE_SSL
          value: "false"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
  - port: 3000
    targetPort: 3000